dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'

networks:
  rinkeby:
    eth_usd_price_feed : '0xF79D6aFBb6dA890132F9D7c355e3015f15F3406F'
    verify : True
  mainnet-fork-dev:
    eth_usd_price_feed : '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify : False  
  development:
    verify : False  
  ganache_mumbai :
    verify : False
    
dotenv : .env
wallets : 
  from_key : ${PRIVATE_KEY}